# Generated by Django 4.1.1 on 2022-10-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alphachanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('price', models.IntegerField(max_length=100)),
            ],
        ),
    ]
