# Generated by Django 4.1.1 on 2022-10-07 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Alphachanel', '0002_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisment',
            name='description',
            field=models.CharField(default='', max_length=1000, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='advertisment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
