# Generated by Django 4.1.1 on 2022-10-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alphachanel', '0003_advertisment_created_at_advertisment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='price',
            field=models.FloatField(default=0, verbose_name='цена'),
        ),
        migrations.AddField(
            model_name='advertisment',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='кол-во просмотров'),
        ),
    ]
