# Generated by Django 4.1.1 on 2022-10-07 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alphachanel', '0004_advertisment_price_advertisment_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusAdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='advertisment',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alphachanel.statusadv'),
        ),
    ]
