# Generated by Django 4.1.1 on 2022-10-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alphachanel', '0005_statusadv_advertisment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisment',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelTable(
            name='advertisment',
            table='advertisement',
        ),
    ]
