# Generated by Django 4.1.1 on 2022-10-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alphachanel', '0006_alter_advertisment_options_alter_advertisment_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='title',
            field=models.CharField(db_index=True, max_length=1000),
        ),
    ]
