# Generated by Django 4.1.1 on 2022-10-11 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alphachanel', '0007_alter_advertisment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alphachanel.statusadv', verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='statusadv',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Статус'),
        ),
    ]
