# Generated by Django 4.1.2 on 2022-10-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alphachanel', '0009_alter_equipment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.IntegerField(),
        ),
    ]
