# Generated by Django 4.1.1 on 2022-10-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('biography', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='Country',
            new_name='country',
        ),
    ]
