# Generated by Django 4.1.2 on 2022-10-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='personal_page',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='author',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='university',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
