# Generated by Django 4.1.2 on 2022-10-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0006_rename_autrhors_book_author_publisher_sold_books_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='is_active',
            field=models.BooleanField(choices=[('A', 'active'), ('NA', 'not_active')], default=False),
        ),
    ]
