# Generated by Django 4.1.2 on 2022-10-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0007_alter_publisher_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'active'), (False, 'not_active')], default=False),
        ),
    ]
