# Generated by Django 4.1.2 on 2022-10-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
    ]
