# Generated by Django 4.1.2 on 2022-10-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employment', '0002_alter_vacancy_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
    ]
